package eh223im_assign3.count_words;

public class StrinTest {
    public static void main(String[] args) {
        String s = "[a, I, s, X, Y, be, He, eg, of, an, do, in, as, at, on, is, ADD, so, had, to, or, by, and, era, can, the, are, far, has, use, let, His, made, who, each, for, need, area, Von, key, art, code, wage, lake, box, half, how, card, free, same, been, tape, huge, late, than, have, time, such, them, were, Some, boat, more, that, cams, jobs, task, both, will, with, ones, step, This, form, play, bump, they, speed, less, unit, Many, which, sets, large, four, most, model, text, while, trend, there, areas, These, COBOL, wages, decks, could, level, cards, TOTAL, became, paper, cases, leaps, whose, royal, other, cloth, called, still, newer, curve, robot, Babbage, tasks, lower, power, raised, prior, about, reader, allow, forms, Engine, known, second, making, first, Every, record, career, Herman, impact, having, people, source, simple, castle, easier, number, toward, enough, modern, moving, series, around, weaves, typing, format, refined, special, faster, created, machine, crafted, reading, likely, instead, floated, deeply, todays, binary, easily, levers, storage, entered, unclear, follow, produce, adopted, subject, guests, devices, several, memory, weaving, earlier, program, Charles, formula, mostly, overhead, specify, Despite, Another, require, language, parties, develop, Fortran, decrease, rebuilt, drummer, perform, compared, pattern, brought, increase, quickly, original, control, familiar, symbolic, economic, Jacquard, usually, variety, editors, hardware, rhythms, machines, learning, invented, drinking, AlJazari, without, Wikipedia, entering, offshore, services, addition, Although, compiler, software, History, benefits, century, behavior, programs, concerns, continue, assembly, notation, plugboard, directly, developed, entirely, languages, Computer, patterns, including, automatic, mechanism, dependent, musicians, converted, different, entertain, terminals, Hollerith, twentieth, AlJazaris, operation, commercial, addresses, importing, programmed, industry, abstracted, decisions, locations, pasteboard, Tabulator, invention, equipment, Analytical, countries, increasing, additional, Tabulating, controlled, specifying, plugboards, progressed, computers, experienced, programmer, particular, processing, complicated, attractive, foundation, lowerlevel, underlying, originally, performance, innovation, relatively, percussion, represented, inventions, programming, programmable, Throughout, encyclopedia, information, outsourcing, programmers, inexpensive, corrections, instruction, architecture, applications, increasingly, sophisticated, calculations, counterparts, instructions, abbreviations, painstakingly, opportunities, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null, null]\n";
        String[] s1 = s.split(",");

        System.out.println(s1.length);
    }
}
